config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles do
    resources :comments
  end
  get 'dashboard', to: 'estates#dashboard', as: 'estate_dashboard'
  get 'favoritos', to: 'estates#favorite', as: 'estate_favorite'
  delete 'propiedad/foto/:id', to: 'estates#delete_photo', as: 'delete_photo'
  post 'estates/:estate_id/visits/:id', to: 'visits#update', as: 'update_visit'
  # resources :type
  # resources :category
  resources :estates do
    resources :likes
    resources :visits
  end
  post 'visits', to: 'visits#create', as: 'create_visit'
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  root to: 'estates#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :url, presence: true
  validates :phone, presence: true
  validates :user_id, presence: true
  has_many :comments, dependent: :destroy

  validates :phone, length: { maximum: 12 }
  validates :secondary_number, length: { maximum: 12 }

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: :show

  # GET /profiles
  # GET /profiles.json
  def index
    @profiles = Profile.all
  end

  # GET /profiles/1
  # GET /profiles/1.json
  def show
    @comments = Comment.where("profile_id = ?", params[:id])
    @rate = @profile.comments.average(:rate) 
    @estates = Estate.where(user_id: @profile.user_id)
    @estates_published = Estate.joins(:category).group('categories.name').where(user_id: @profile.user_id).count()
  end

  # GET /profiles/new
  def new
    @profile = current_user.build_profile
  end

  # GET /profiles/1/edit
  def edit
    @profile = current_user.profile
  end

  # POST /profiles
  # POST /profiles.json
  def create
    @profile = current_user.build_profile(profile_params)

    respond_to do |format|
      if @profile.save
        format.html { redirect_to @profile, notice: 'Tu perfil se ha creaado' }
        format.json { render :show, status: :created, location: @profile }
      else
        format.html { render :new }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /profiles/1
  # PATCH/PUT /profiles/1.json
  def update
    @profile = current_user.profile
    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to @profile, notice: 'Tu perfil ha sido actualizado' }
        format.json { render :show, status: :ok, location: @profile }
      else
        format.html { render :edit }
        format.json { render json: @profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /profiles/1
  # DELETE /profiles/1.json
  def destroy
    @profile = current_user.profile
    @profile.destroy
    respond_to do |format|
      format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_profile
      @profile = Profile.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def profile_params
      params.require(:profile).permit(:url, :phone, :user_id, :email, :address, :location_id, :secondary_number, :facebook_profile, :twitter_profile, :instagram_profile, :job_position, :zone)
    end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/profiles/_form.html.erb
<%= form_with(model: profile, local: true) do |form| %>
  <% if profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(profile.errors.count, "error") %> prohibited this profile from being saved:</h2>

      <ul>
      <% profile.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">
      <div class="field">
        <%= form.label :Tu_pagina_web %>
        <%= form.text_field :url, class: "form-control", placeholder: "Tu pagina" %>
      </div>

      <div class="field">
        <%= form.label :Numero_de_contacto %>
        <%= form.number_field :phone, class: "form-control", placeholder: "Tu numero de contacto" %>
      </div>

      <div class="field">
        <%= form.label :direccion %>
        <%= form.text_field :address, class: "form-control", placeholder: "Tu direccion" %>
      </div>

      <div class="field">
        <%= form.label :correo_de_contacto%>
        <%= form.text_field :email, class: "form-control", placeholder: "Tu correo de contacto" %>
      </div>

      <div class="field">
        <%= form.label :numero_secundario%>
        <%= form.text_field :secondary_number, class: "form-control", placeholder: "Tu numero de contacto secundario" %>
      </div>

      <div class="field">
        <%= form.label :cuenta_de_facebook%>
        <%= form.text_field :facebook_profile, class: "form-control", placeholder: "Tu cuenta de Facebook" %>
      </div>

      <div class="field">
        <%= form.label :cuenta_de_twitter %>
        <%= form.text_field :twitter_profile, class: "form-control", placeholder: "Tu cuenta de Twitter" %>
      </div>

      <div class="field">
        <%= form.label :cuenta_de_instagram %>
        <%= form.text_field :instagram_profile, class: "form-control", placeholder: "Tu cuenta de Instagram" %>
      </div>

      <div class="field">
        <%= form.label :posicion_laboral %>
        <%= form.text_field :job_position, class: "form-control", placeholder: "Tu cuenta de Instagram" %>
      </div>

      <div class="field">
        <%= form.label :zona_de_trabajo %>
        <%= form.text_field :zone, class: "form-control", placeholder: "Tu cuenta de Instagram" %>
      </div>

      

      <div class="actions">
        <%= form.submit "Guarda los cambios", class: "btn btn-lg btn-primary btn-lg btn-block my-5" %>
      </div>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="container">
    <h1 class="text-center mt-5">Edita tu Perfil de Usuario</h1>

    <%= render 'form', profile: @profile %>

    <%= link_to 'Mostrar tu perfil', @profile %> 
</div>

app/views/profiles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Profiles</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Telefono</th>
      <th>Nota promedio</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @profiles.each do |profile| %>
      <tr>
        <td><%= profile.user.first_name %></td>
        <td><%= profile.phone %></td>
        <td><%= profile.comments.average(:rate) %></td>
        <td><%= link_to 'Show', profile %></td>
        <td><%#= link_to 'Edit', edit_profile_path(profile) %></td>
        <td><%#= link_to 'Destroy', profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>


<%#= link_to 'New Profile', new_profile_path %>

app/views/profiles/new.html.erb
<h1 class="text-center mt-5">Optimiza tu Perfil</h1>

<div class="container">
    <%= render 'form', profile: @profile %>

    <%= link_to 'Pagina de Inicio', root_path %>
</div>

app/views/profiles/show.html.erb
<p id="notice"><%= notice %></p>

 
<div class="container mt-5">
    <div class="main-body">
    
          <div class="row gutters-sm">
            <div class="col-md-4 mb-3">
              <div class="card">
                <div class="card-body">
                  <div class="d-flex flex-column align-items-center text-center">

                  <% if @profile.user.avatar.attached? %>
                    <%= image_tag @profile.user.avatar, size: '150x150', class: "rounded-circle mx-5" %>
                  <% else %>
                    <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                  <% end %>

                    <div class="mt-3">
                      <%= @profile.user.first_name %> <%= @profile.user.last_name %>
                      <p class="text-secondary mb-1"><%= @profile.job_position %></p>
                      <p class="text-muted font-size-sm"><%= @profile.zone %></p>
                      <button class="btn btn-primary">Sigueme</button>
                      <button class="btn btn-outline-primary">Message</button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card mt-3">
                <ul class="list-group list-group-flush">
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-globe mr-2 icon-inline"><circle cx="12" cy="12" r="10"></circle><line x1="2" y1="12" x2="22" y2="12"></line><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"></path></svg>Website</h6>
                    <span class="text-secondary"><%= @profile.url %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-twitter mr-2 icon-inline text-info"><path d="M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z"></path></svg>Twitter</h6>
                    <span class="text-secondary"><%= @profile.twitter_profile %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-instagram mr-2 icon-inline text-danger"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>Instagram</h6>
                    <span class="text-secondary"><%= @profile.instagram_profile %></span>
                  </li>
                  <li class="list-group-item d-flex justify-content-between align-items-center flex-wrap">
                    <h6 class="mb-0"><svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-facebook mr-2 icon-inline text-primary"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>Facebook</h6>
                    <span class="text-secondary"><%= @profile.facebook_profile %></span>
                  </li>
                </ul>
                <div class="container mt-5">
                  <% if current_user %>
                    <% if current_user.id == @profile.user_id %>
                    <ul class="h5">
                      <li><%= link_to  "Edita tu Panel de Usuario", edit_profile_path %></li>
                      <li><%= link_to  "Edita tus datos de Acceso", edit_user_registration_path %></li>
                    <% end %>
                      <li><%= link_to 'Volver a Inicio', root_path, class:"text-primary" %></li>
                    </ul>
                  <% end %>
                </div>
              </div>
            </div>
            <div class="col-md-8">
              <div class="card mb-3">
                <div class="card-body">
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Nombre</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @profile.user.first_name %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Email</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @profile.email %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Numero de Contacto</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @profile.phone %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Numero Secundario</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @profile.secondary_number %>
                    </div>
                  </div>
                  <hr>
                  <div class="row">
                    <div class="col-sm-3">
                      <h6 class="mb-0">Direccion</h6>
                    </div>
                    <div class="col-sm-9 text-secondary">
                      <%= @profile.address %>
                    </div>
                  </div>
                </div>
              </div>
            
        <div>
          <h2 class="text-primary my-4">Este usuario tiene una puntuacion de: <%= @rate == nil ? 0 : @rate.round(2) %> / 10</h2>
        </div>
        
      <!-- Input de comentarios y calificaciones -->

      <% if current_user %>
        <% if current_user.id != @profile.user_id %>
            <h4 class="ml-2 mt-5 mb-3 ">Ingresa tu experiencia con este usuario</h4>

                <%= form_with(model: [@profile, @profile.comments.build]) do |f| %>
                  <div class="form-group col-md-12">
                    <div class="form-row">
                      <%= f.text_area :content, class: "form-control" , placeholder: "Escribe tu experiencia con este usuario" %>
                    </div>
                  </div> 

                  <div class="form-group col-md-12">
                    <div class="form-row">
                      <%= f.select :rate, options_for_select(0..10), { prompt: "Califica a este usuario" } %>
                    </div>
                  </div> 
                      <%= f.submit "Guardar", class: "btn btn-primary ml-2" %>
                <% end %>
            <% end %>
      <% end %>
        


            <!-- Montaje de comentarios y calificaciones -->
              <hr>
              <h2 class="ml-2 mt-5">Comentarios</h2>
              <div class="my-5 list-group list-group-flush">
                <% @comments.order(created_at: :desc).each do |comment| %>
                  <h5>
                    <strong><%= link_to comment.user.first_name, comment.user.profile %></strong > escribio <small><%= time_ago_in_words(comment.created_at) %></small>
                  </h5>

                  <h3>
                    <%= comment.content %>
                    <small class="text-primary">Calificacion: 
                    <%= comment.rate %>
                    </small>
                  </h3>
                  <hr><hr>
                    <%#= link_to  "Editar", model %>
                <% end %>
              </div>


              <%= column_chart @estates_published, colors: ["#607D8B", "#3F51B5"] %>

              <% if @estates.empty? %>
                <h2 class="text-center my-5"><%= "Este usuario no tiene propiedades publicadas" %></h2>
                <i class="fas fa-times-circle fa-5x d-flex justify-content-center align-items-center"></i>
              <% else %>
                <h2 class="text-center my-5"><%= "Estas son las propiedades publicadas por este usuario" %></h2>
                <table class="table table-striped mt-5 container"> 
                  <thead>
                    <tr>
                      <th>Tipo</th>
                      <th>Categoria</th>
                      <th>Ubicacion</th>
                      <th>Ciudad</th>
                      <th>Precio</th>
                      <th colspan="3"></th>
                    </tr>
                  </thead>

                  <tbody>
                      <% @estates.each do |estate| %>
                        <tr>
                          <td><%= estate.type.mode %></td>
                          <td><%= estate.category.name %></td>
                          <td><%= estate.address %></td>
                          <td><%= estate.location.name %></td>
                          <td><%= estate.price %></td>
                          <% if estate.photos.empty? %>
                            <td><%= image_tag("house.jpg", size: "120x80") %></td>
                          <% else %>
                            <td><%= image_tag estate.photos[0].variant(resize: '120x80') %></td>
                          <% end %>

                          <td><%= link_to 'Mostrar', estate %></td>
                        </tr>
                      <% end %>
                  </tbody>
                </table>
              <% end %>
          </div>
        </div> 
      </div>
  </div> 
</div>