config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :profiles do
    resources :comments
  end
  get 'dashboard', to: 'estates#dashboard', as: 'estate_dashboard'
  get 'favoritos', to: 'estates#favorite', as: 'estate_favorite'
  delete 'propiedad/foto/:id', to: 'estates#delete_photo', as: 'delete_photo'
  post 'estates/:estate_id/visits/:id', to: 'visits#update', as: 'update_visit'
  # resources :type
  # resources :category
  resources :estates do
    resources :likes
    resources :visits
  end
  post 'visits', to: 'visits#create', as: 'create_visit'
  devise_for :users, controllers: { 
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks',
    sessions: 'users/sessions'
  }
  root to: 'estates#home'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/estate.rb
class Estate < ApplicationRecord
    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many_attached :photos
    validates :photos, content_type: [:png, :jpg, :jpeg]
    validates :photos, limit: { max: 6 }

    has_many :visits, dependent: :destroy

    belongs_to :location, optional: true
    belongs_to :category, optional: true
    belongs_to :type, optional: true

    #validaciones
    validates :location_id, presence: true
    validates :address, presence: true
    validates :type_id, presence: true
    validates :price, presence: true
    validates :description, length: { maximum: 550 }



    scope :latest, -> { order created_at: :desc }
    # enum type: [:venta, :arriendo]
end

app/controllers/estates_controller.rb
class EstatesController < ApplicationController
  before_action :set_estate, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :create, :destroy]
  before_action :set_sidebar, except: [:show]
  # load_and_authorize_resource

  # GET /estates
  # GET /estates.json
  def index
    @q = Estate.ransack(params[:q])
    @estates = @q.result.includes(:location, :category, :type)
    # @estates = Estate.with_attached_photos.all
    # @locations = Location.all
    # @types = Type.all
    # @categories = Category.all
    # @estate.punch(request)
  end

  def home
    @q = Estate.ransack(params[:q])
    @estates = @q.result.includes(:location, :category, :type)
    @estates_random = Estate.where(id: Estate.pluck(:id).sample(6))
    @categories = Category.all
  end

  def favorite
    @likes = Like.where(user_id: current_user.id)
    @types = Type.all
    @categories = Category.all
    @locations = Location.all
  end

  def dashboard
    @estates = Estate.where(user_id: current_user.id)
    @types = Type.all
    @categories = Category.all
    @locations = Location.all
  end

  # GET /estates/1
  # GET /estates/1.json
  def show
    @user = @estate.user
    # @pre_like = @estate.likes.find { |like| like.user_id == current_user.id}
    @visit = Visit.new
    @q = Estate.ransack(params[:q])
    @estates = @q.result.includes(:location, :category, :type)
    
    @visit_estate = Visit.where(estate_id: @estate.id)

    respond_to do |format|
      format.html {  }
      format.json { render json: @visit_estate }
    end
  end

  # GET /estates/new
  def new
    @estate = Estate.new
    @locations = Location.all
    @types = Type.all
    @categories = Category.all
  end

  # GET /estates/1/edit
  def edit
    @locations = Location.all
    @types = Type.all
    @categories = Category.all
  end

  # POST /estates
  # POST /estates.json
  def create
    @estate = Estate.new(estate_params)
    @estate.user_id = current_user.id
    @types = Type.all
    @categories = Category.all
    @locations = Location.all

    respond_to do |format|
      if @estate.save
        format.html { redirect_to @estate, notice: 'Estate was successfully created.' }
        format.json { render :show, status: :created, location: @estate }

        estate_mail(
          mail: current_user.email, 
          subject: 'Tu propiedad se ha publicado con exito!',
          message: 'Tu propiedad ha sido creada con exito!'
        )
      else
        format.html { render :new }
        format.json { render json: @estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estates/1
  # PATCH/PUT /estates/1.json
  def update
    @types = Type.all
    @categories = Category.all
    @locations = Location.all
    respond_to do |format|
      if @estate.update(estate_params)
        format.html { redirect_to @estate, notice: 'Estate was successfully updated.' }
        format.json { render :show, status: :ok, location: @estate }
      else
        format.html { render :edit }
        format.json { render json: @estate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estates/1
  # DELETE /estates/1.json
  def destroy
    @estate.destroy
    respond_to do |format|
      format.html { redirect_to estates_url, notice: 'Estate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def delete_photo
    @att = ActiveStorage::Attachment.find(params[:id])
    # @estate = @att.record
    @att.purge
    # render :edit, location: @estate
    redirect_back(fallback_location: request.referer)
    
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estate
      @estate = Estate.find(params[:id])
    end

    def set_sidebar
        @show_sidebar = true
    end

    # Only allow a list of trusted parameters through.
    def estate_params
      params.require(:estate).permit(:name, :address, :price, :rooms, :bathrooms, :parking, :storage, :description, :location_id, :type_id, :category_id, photos: [])
    end

    def visit_params
      params.require(:visit).permit(:content, :start, :end, :estate_id, :visit_id, :user_id)
  end

end
   

app/helpers/estates_helper.rb
module EstatesHelper

    def estate_thumbnail estate
       img = estate.photos.present? ? estate.photos.thumb.url : "placeholder.png"
       image_tag img, class: "estate-thumb"
    end
end

app/views/estates/dashboard.html.erb
<p id="notice"><%= notice %></p>
  
<div class="hero-image2 text-center">
  <!-- Navbar de usuario -->
  <% if user_signed_in? %>
      <%= link_to  "Mis propiedades", estate_dashboard_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to  "Mis Propiedades Favoritas", estate_favorite_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to  "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "mt-3 mx-3 text-white" %>
      <%= link_to  "Edita tu perfil", edit_user_registration_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to 'Publica una propiedad', new_estate_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to 'Inicio', root_path, class: "mt-3 mx-5 text-white" %>
      <span class="ml-5 text-white"><%= current_user.email %></span>
      
      <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, size: '70x70', class: "rounded-circle mx-5" %>
        <% else %>
          <%= image_tag("default_profileB.jpg", size: '70x70', class: "rounded-circle mx-5") %>
        <% end %>
  <% else %>
      <%= link_to  "Inicia Sesion", new_user_session_path, class: "mt-3 ml-3 text-white" %>
      <%= link_to  "Registrate", new_user_registration_path, class: "mt-3 ml-3 text-white" %>
      <%= link_to 'Inicio', root_path, class: "mt-3 mx-5 text-white" %>
  <% end %>


  <!-- Jumbotron para titulo comercial de la plataforma -->
  <div class="hero-text">
    <h1 class="font-weight-bold">CommercialCity</h1>
    <h3 class="mb-3">La comunidad digital del mundo inmobiliario</h3>
  </div>
</div>


<table class="table table-striped container my-3"> 
  <thead>
    <tr>
      <th>Tipo</th>
      <th>Categoria</th>
      <th>Ubicacion</th>
      <th>Ciudad</th>
      <th>Precio</th>
      <th>Dormitorios</th>
      <th>Baños</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @estates.each do |estate| %>
      <tr>
        <td><%= estate.type.mode %></td>
        <td><%= estate.category.name %></td>
        <td><%= estate.address %></td>
        <td><%= estate.location.name %></td>
        <td><%= estate.price %></td>
        <td><%= estate.rooms %></td>
        <td><%= estate.bathrooms %></td>
        <% if estate.photos.empty? %>
          <td><%= image_tag("house.jpg", size: "120x80") %></td>
        <% else %>
          <td><%= image_tag estate.photos[0].variant(resize: '120x80') %></td>
        <% end %>

  
        <td><%= link_to 'Mostrar', estate %></td>
        <td><%= link_to 'Edita Tu Propiedad', edit_estate_path(estate) %></td>
        <td><%= link_to 'Elimina la publicacion', estate, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-5">
    <%= render 'footer' %>
</div>

app/views/estates/favorite.html.erb
<p id="notice"><%= notice %></p>
  
<div class="hero-image3 text-center">
  <!-- Navbar de usuario -->
  <% if user_signed_in? %>
      <%= link_to  "Mis propiedades", estate_dashboard_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to  "Mis Propiedades Favoritas", estate_favorite_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to  "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "mt-3 mx-3 text-white" %>
      <%= link_to  "Edita tu perfil", edit_user_registration_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to 'Publica una propiedad', new_estate_path, class: "mt-3 mx-5 text-white" %>
      <%= link_to 'Inicio', root_path, class: "mt-3 mx-5 text-white" %>
      <span class="ml-5 text-white"><%= current_user.email %></span>

        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, size: '70x70', class: "rounded-circle mx-5" %>
        <% else %>
          <%= image_tag("default_profileB.jpg", size: '70x70', class: "rounded-circle mx-5") %>
        <% end %>
        
  <% else %>
      <%= link_to  "Inicia Sesion", new_user_session_path, class: "mt-3 ml-3 text-white" %>
      <%= link_to  "Registrate", new_user_registration_path, class: "mt-3 ml-3 text-white" %>
      <%= link_to 'Inicio', root_path, class: "mt-3 mx-5 text-white" %>
  <% end %>


  <!-- Jumbotron para titulo comercial de la plataforma -->
  <div class="hero-text">
    <h1 class="font-weight-bold">CommercialCity</h1>
    <h3 class="mb-3">La comunidad digital del mundo inmobiliario</h3>
  </div>
</div>

<% if @likes.empty? %>
  <h2 class="text-center my-5"><%= "No tienes propiedades favoritas" %></h2>
  <i class="fas fa-times-circle fa-5x d-flex justify-content-center align-items-center"></i>
<% else %>

  <table class="table table-striped container my-3"> 
    <thead>
      <tr>
        <th>Tipo</th>
        <th>Categoria</th>
        <th>Ubicacion</th>
        <th>Ciudad</th>
        <th>Precio</th>
        <th>Dormitorios</th>
        <th>Baños</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @likes.each do |like| %>
        <tr>
          <td><%= like.estate.category.name %></td>
          <td><%= like.estate.type.mode %></td>
          <td><%= like.estate.address %></td>
          <td><%= like.estate.location.name %></td>
          <td><%= like.estate.price %></td>
          <td><%= like.estate.rooms %></td>
          <td><%= like.estate.bathrooms %></td>
          <td><%= link_to  "Mostrar", estate_path(like.estate_id) %></td>
          <% if like.estate.photos.empty? %>
            <td><%= image_tag("house.jpg", size: "120x80") %></td>
          <% else %>
            <td><%= image_tag like.estate.photos[0].variant(resize: '120x80') %></td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<div class="mt-5">
    <%= render 'footer' %>
</div>
 

app/views/estates/index.html.erb
<p id="notice"><%= notice %></p>
  
<div class="hero-image text-center">
  <!-- Navbar de usuario -->
  <div class="container ">
    <% if user_signed_in? %>
        <%= link_to  "Mis propiedades", estate_dashboard_path, class: "mt-3 mx-5 text-white" %>
        <%#= link_to  "Mis Propiedades Favoritas", estate_favorite_path, class: "mt-3 mx-5 text-white" %>
        <%#= link_to  "Edita tu perfil", edit_user_registration_path, class: "mt-3 mx-5 text-white" %>
        <%= link_to 'Publica una propiedad', new_estate_path, class: "mt-3 mx-5 text-white" %>
        <%= link_to  "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "mt-3 mx-3 text-white" %>
        <%#= link_to 'Inicio', root_path, class: "mt-3 mx-5 text-white" %>
        <span class="ml-5 text-white"><%= current_user.email %></span>
        <%#= image_tag(current_user.avatar_thumbnail, size: '70x70', class: "rounded-circle mx-5") %>
    <% else %>
        <%= link_to  "Inicia Sesion", new_user_session_path, class: "mt-3 ml-3 text-white" %>
        <%= link_to  "Registrate", new_user_registration_path, class: "mt-3 ml-3 text-white" %>
        <%#= link_to 'Inicio', root_path, class: "mt-3 mx-5 text-white" %>
    <% end %>

    <!-- Jumbotron para titulo comercial de la plataforma -->
    <div class="hero-text">
      <h1 class="font-weight-bold">CommercialCity</h1>
      <h3 class="mb-3">La comunidad digital del mundo inmobiliario</h3>

      <%= render 'search_form' %>
    </div>
  </div>
</div>

<% if @estates.empty? %>
  <h2 class="text-center my-5"><%= "No hay resultados" %></h2>
  <i class="fas fa-times-circle fa-5x d-flex justify-content-center align-items-center"></i>
<% else %>
  <table class="table table-striped mt-5 container"> 
    <thead>
      <tr>
        <th>Tipo</th>
        <th>Categoria</th>
        <th>Ubicacion</th>
        <th>Ciudad</th>
        <th><%= sort_link(@q, :price, "Precio") %></th>
        <th><%= sort_link(@q, :rooms, "Dormitorios") %></th>
        <th>Baños</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
        <% @estates.each do |estate| %>
          <tr>
            <td><%= estate.type.mode %></td>
            <td><%= estate.category.name %></td>
            <td><%= estate.address %></td>
            <td><%= estate.location.name %></td>
            <td><%= estate.price %></td>
            <td><%= estate.rooms %></td>
            <td><%= estate.bathrooms %></td>
            <% if estate.photos.empty? %>
              <td><%= image_tag("house.jpg", size: "120x80") %></td>
            <% else %>
              <td><%= image_tag estate.photos[0].variant(resize: '120x80') %></td>
            <% end %>

            <td><%= link_to 'Mostrar', estate %></td>
          </tr>
        <% end %>
    </tbody>
  </table>
<% end %>

<div class="mt-5">
    <%= render 'footer' %>
</div>


  




        

app/views/estates/new.html.erb
<div class="hero-image text-center">
  <!-- Navbar de usuario -->
  <% if user_signed_in? %>
        <%if current_user.profile == nil %>
          <%= link_to  "Optimiza tu perfil", new_profile_path, class: "mt-5 mx-5 text-white" %>
        <% else %>
          <%= link_to  "Tu Perfil", current_user.profile, class: "mt-5 mx-5 text-white" %>
        <% end %>
      <%= link_to  "Mis propiedades", estate_dashboard_path, class: "mt-5 mx-5 text-white" %>
      <%= link_to  "Mis Propiedades Favoritas", estate_favorite_path, class: "mt-5 mx-5 text-white" %>
      <%= link_to  "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "mt-3 mx-3 text-white" %>
      <%= link_to  "Edita tu perfil", edit_user_registration_path, class: "mt-5 mx-5 text-white" %>
      <%= link_to 'Publica una propiedad', new_estate_path, class: "mt-5 mx-5 text-white" %>
      <span class="ml-5 text-white"><%= current_user.email %></span>
      <%#= image_tag(current_user.avatar_thumbnail, size: '70x70', class: "rounded-circle mx-5") || image_tag("default_profileB.jpg") %>
      <div class="hero-text">
        <h1 class="font-weight-bold">CommercialCity</h1>
        <h3 class="mb-3">Publica tu propiedad con nosotros</h3>
      </div>
  </div>
  <% else %>
      <%= link_to  "Inicia Sesion", new_user_session_path, class: "mt-3 ml-3 text-white font-weight-bold" %>
      <%= link_to  "Registrate", new_user_registration_path, class: "mt-3 ml-3 text-white font-weight-bold" %>
      <div class="hero-text">
        <h1 class="font-weight-bold">CommercialCity</h1>
        <h3 class="mb-3">La comunidad digital del mundo inmobiliario</h3>
      </div>
  <% end %>
</div>
        <%= render 'form', estate: @estate %>

app/views/estates/show.html.erb
<div class="hero-image-show-estate container">
  <% if user_signed_in? %>
        <%if current_user.profile == nil %>
          <%= link_to  "Optimiza tu Panel de Contacto", new_profile_path, class: "text mt-5 mx-5 text-white h5 text-decoration-none" %>
        <% else %>
          <%= link_to  "Tu Panel de Contacto", current_user.profile, class: "text mt-5 mx-5 text-white h5 text-decoration-none" %>
        <% end %>
      <%= link_to  "Mis propiedades", estate_dashboard_path, class: "text mt-5 mx-5 text-white h5 text-decoration-none" %>
      <%= link_to  "Edita tu perfil", edit_user_registration_path, class: "text mt-5 mx-5 text-white h5" %>
      <%= link_to 'Publica una propiedad', new_estate_path, class: "text mt-5 mx-5 text-white h5" %>
      <%= link_to  "Cerrar Sesion", destroy_user_session_path, method: :delete, class: "text mt-4 mx-4 text-white h5" %>
      <span class="ml-5 text-white"><%= current_user.email %></span>
        <% if current_user.avatar.attached? %>
          <%= image_tag current_user.avatar, size: '50x50', class: "rounded-circle mx-5" %>
        <% else %>
          <%= image_tag("default_profileB.jpg", size: '50x50', class: "rounded-circle mx-5") %>
        <% end %>

</div>

  <% else %>
      <div class="text-center" >
        <%= link_to "Inicia Sesion", new_user_session_path, class: "text ml-3 text-white text-decoration-none" %>
        <%= link_to  "Registrate", new_user_registration_path, class: "text ml-3 text-white text-decoration-none" %>
      </div>
  <% end %>
</div>
          




    <div class="container show-header">
      <section class="py-5">
        <span class="display-4"><%= @estate.type.mode %> de <%= @estate.category.name %></span><br>
        <i class="fas fa-map-marker-alt fa-2x text-secondary"></i>  <span class="h1"><%= @estate.address %>, <%= @estate.location.name %>, </span>
        <span class="h2 text-secondary mb-3">Region de <%= @estate.location.region %></span><p class="h5 mb-3 text-muted">Fecha de Publicacion: <%= @estate.created_at.strftime("%Y-%m-%d") %></p>
      </section>
    </div>
        <div class="container text-center mb-3">
          <div class="row bg-light">
            <div class="col-3">
              <p class="m-0 h4"><strong>Habitaciones</strong></p>
                  <span class="lead h4"><%= @estate.rooms %></span>
            </div>
            <div class="col-3">
              <p class="m-0 h4"><strong>Baños</strong></p>
                  <span class="lead"><%= @estate.bathrooms %></span>
            </div>
            <div class="col-3 pl-0">
              <p class="m-0 h4"><strong>Estacionamiento</strong></p>
                  <span class="lead"><%= @estate.parking %></span>
            </div>
            <div class="col-3">
              <p class="m-0 h4"><strong>Bodega</strong></p>
                  <span class="lead"><%= @estate.storage %></span>
            </div>
        </div>
      </div>

<div id="carouselExampleControls" class="carousel slide container" data-ride="carousel" align="center">
  <div class="carousel-inner">
    <div class="carousel-item active">
      <%= @estate.photos.first.nil? ? image_tag("house.jpg") : image_tag(@estate.photos.first) %>
    </div>
    <div class="carousel-item">
      <%= @estate.photos.second.nil? ? image_tag("house.jpg") : image_tag(@estate.photos.second) %>
    </div>
    <div class="carousel-item">
      <%= @estate.photos.third.nil? ? image_tag("house.jpg") : image_tag(@estate.photos.third) %>
    </div>
    <div class="carousel-item">
      <%= @estate.photos.fourth.nil? ? image_tag("house.jpg") : image_tag(@estate.photos.fourth) %>
    </div>
    <div class="carousel-item">
      <%= @estate.photos.fifth.nil? ? image_tag("house.jpg") : image_tag(@estate.photos.fifth) %>
    </div>
        <div class="carousel-item">
      <%= @estate.photos[5].nil? ? image_tag("house.jpg") : image_tag(@estate.photos[5]) %>
    </div>

  </div>
  <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>

<div class="container mt-5 pt-3">
  <div class="row">
    <div class="col-12">
      <div class="row">
        <div class="col-6">
        </div>
    </div>
    
      <div class="row mb-4">
        <div class="col-md-3">
          <div class="card">
            <div class="card-body">
              <div class="d-flex flex-column align-items-center text-center">

                <% if @estate.user.avatar.attached? %>
                  <%= image_tag @estate.user.avatar, size: '150x150', class: "rounded-circle mx-5" %>
                <% else %>
                  <img src="https://bootdey.com/img/Content/avatar/avatar7.png" alt="Admin" class="rounded-circle" width="150">
                <% end %>

                  <div class="mt-3">
                    <%= @estate.user.first_name %> <%= @estate.user.last_name %>
                    <p class="text-secondary mb-1"><%= @estate.user.profile.job_position %></p>
                    <p class="text-muted font-size-sm"><%= @estate.user.profile.zone %></p>
                    <%= link_to  "Perfil del usuario", @estate.user.profile, class:"btn btn-primary text-white" %>
                  </div>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-9">
          <div class="card w-100 mb-3 h-100">
            <div class="card-body">
              <h5 class="card-title text-primary strong h4">Descripcion de la Propiedad</h5>
              <p class="card-text w-100"><%= @estate.description %></p>
            </div>
            <ul class="list-group list-group-flush">
              <li class="list-group-item h5"><strong>Ubicacion:</strong> <%= @estate.address %>, <%= @estate.location.name %></li>
              <li class="list-group-item h5"><strong>Precio:</strong> <%= @estate.price > 0 ? number_to_currency(@estate.price, precision: 0) : "En Venta" %></li>
              <li class="list-group-item h6"><strong>Numero de contacto: </strong><%= @estate.user.profile.phone %> / <strong>Email de contacto: </strong><%= @estate.user.profile.email %></li>
            </ul>
          </div>
        </div>
      </div>


      <%
=begin%>
 <div class="row border-top border-bottom mt-5 mb-4 pt-4 pb-4">
        <div class="col-6 text-left">

          <% if current_user %>
            <% if current_user.id == @estate.user_id %>
              <%= @estate.likes.count %> <%= (@estate.likes.count) == 1 ? 'Usuario interesado en tu propiedad' : 'Usuarios interesados en tu propiedad'%>
            <% end %>
            
            <% if @pre_like %>
              <%= button_to 'Ya no me interesa', estate_like_path(@estate, @pre_like), method: :delete, class:"btn btn-primary text-white mt-3" %>
            <% else %>
              <%= button_to 'Me gusta', estate_likes_path(@estate), method: :post, class:"btn btn-primary text-white mt-3" %>
            <% end %>
          <% end %>
        </div>
      </div> 
<%
=end%>
        

          
    </div>
</div>

      <% if current_user %>
          <div class="col-4 h5">
              <%#= render "estates/agent_details" %>
              <%#= link_to  "Perfil del usuario", @estate.user.profile, class:"btn btn-success text-white" %>
              <%= link_to 'Inicio', root_path %>
              <% if current_user.id == @estate.user_id %> |
                <%= link_to 'Edita la propiedad', edit_estate_path(@estate) %> 
              <% end %>
            <% end %>
          </div>
        </div>
    </div>

<div class="container my-5">
  <iframe width="1100" height="450" frameborder="0" style="border:0" src="https://www.google.com/maps/embed/v1/place?key=AIzaSyCX9VNRtLubMN2d0Ku3DBqBB_42U9g5oDk&q=<%= @estate.address %>, <%= @estate.location.name %>" allowfullscreen></iframe>
</div>



<div class="container mt-5">
  <%#= image_tag @estate.photos.first.variant(resize: '900x1500') if @estate.photos.attached? %>
</div>

  <!-- Calendario con formulario para disponibilidad de visitas a la propiedad-->
<h2 class="text-center my-5">Fechas de visita disponibles para mayor informacion</h2>
<div class="container my-5" id="calendar"></div>
<div class="container my-5">

<% if current_user %>
    <% if current_user.id == @estate.user_id %>
      <h3 class="text-center my-5">Agrega fechas de visita disponibles para mayor informacion</h3>
      <%= form_with(model: [ @estate, @visit ], local: true) do |f| %>
        <div class="form-row text-center h4">
          <div class="form-group col-md-4">
            <div>
                <%= f.label :content, "Observaciones" %>
                <%= f.text_field :content, class:"form-control" %>
            </div>
          </div>
          <div class="form-group col-md-4">
            <div>
                <%= f.label :start, "Inicio" %>
                <%= f.datetime_field :start, class:"form-control" %>
            </div>
          </div>
          <div class="form-group col-md-4">
            <div>
                <%= f.label :end, "Termino" %>
                <%= f.datetime_field :end, class:"form-control" %>
            </div>
          </div>

          
            <%= f.submit "Crear fecha", class:"btn btn-primary btn-lg text-center" %>
          
      </div>

    <% end %>
  <% end %>
<% end %>
</div>


<table class="table table-striped container my-5"> 
  <thead>
    <tr>
      <th class="text-center h4">Observaciones</th>
      <th class="text-center h4">Desde</th>
      <th class="text-center h4">Hasta</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody class="align-middle">
    <% @visit_estate.each do |visit| %>
      <tr>
        <td class="text-center align-middle"><%= visit.content %></td>
        <td class="text-center align-middle"><%= visit.start.strftime("%d/%m/%Y a las %H:%M") %></td>
        <td class="text-center align-middle"><%= visit.end.strftime("%d/%m/%Y a las %H:%M") %></td>

        <% if current_user %>
          <% if current_user.id == @estate.user_id %>
            <td><%= link_to 'Edita la fecha', edit_estate_visit_path(@estate, visit), :class => 'btn btn-large btn-primary text-white mt-3' %></td>
            <td><%= link_to 'Borra la fecha', estate_visit_path(@estate, visit), :method => 'delete', :class => 'btn btn-large btn-primary text-white mt-3'  %></td>
          <% end %>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<div class="mt-5">
    <%= render 'footer' %>
</div>

<script>var estateId = <%= @estate.id %></script>